### ISSUE TITLE
Working Router agnostic now, hooray! But, one thing..

### ISSUE THREAD

**Issue by NathanWalker** [angulartics/angulartics2#29] opened 2016-05-11 20:29 UTC
So it looks like `location.subscribe` does fire on first load of the page so you get the initial page track which is awesome.

However, subsequent route changes do not fire through `location.subscribe`.
We can either:

A. suggest that users subscribe to whichever router they are using and track events manually themselves for route changes.
B. try to figure out how to get `Location` wired up correctly to react to route/location changes
C. B may be hindered by a framework bug, not sure. It seems like `location.subscribe` should pick up any url changes, but it doesn't appear so. We could wait until this is fixed, post issue on angular repo, and get some clarity on how to do this best (without a router in the mix) with just `Location`.

I'm still thinking about what the best way forward is.

At any rate, the latest release `does` work to track all events properly (and even the initial page load tracking) **and** works without any dependency on any particular router which is awesome.

**Comment by JonnyBGod** [comment] 2016-05-11 21:40
The does not look like the expected behaviour.

Are you testing with latest router or deprecated one?

I read some reports on "router should change location". I believe this should mean that locations service would capture the change. Added the fact the new router change observable does not pass state. So we would need to check for location state on every route change event.

This looks like a bug to me. Will investigate a bit further.

**Comment by JonnyBGod** [comment] 2016-05-11 22:07
If this is the case we should put this release in "pre-release" mode and document the problem.

https://github.com/angular/angular/blob/master/modules/%40angular/router/test/integration_spec.ts#L51

**Comment by JulioC** [comment] 2016-05-13 01:21
I believe the test you linked is just for the new router.

I'm using the new router and Location.subscribe never gets triggered.

**Comment by NathanWalker** [comment] 2016-05-13 01:24
I think we may want to create an issue for that... at minimum it would help clarify whether it is a framework bug or expected behavior with new router... @JulioC do you mind creating an issue for that on angular repo and we'll see?

**Comment by JulioC** [comment] 2016-05-13 01:42
Filled: https://github.com/angular/angular/issues/8630

**Comment by JulioC** [comment] 2016-05-19 02:40
Looks like the issue won't be solved so quickly. I put together a workaround for it:

```typescript
import {Location} from '@angular/common';
import {Injectable} from '@angular/core';
import {Router} from '@angular/router-deprecated';
import {Angulartics2} from 'angulartics2';

@Injectable()
export class Angulartics2Deprecated extends Angulartics2 {
  constructor(location: Location, router: Router) {
    super(location);
    this.trackRouter(location, router);
  }

  trackRouter(location: Location, router: Router) {
    router.subscribe((value: any) => {
      if (!this.settings.developerMode) {
        var url = location.path();
        if (this.settings.pageTracking.autoTrackVirtualPages && !this.matchesExcludedRouteChild(url)) {
          this.pageTrack.next({
            path: this.settings.pageTracking.basePath.length ? this.settings.pageTracking.basePath + url : location.prepareExternalUrl(url),
            location: location
          });
        }
      }
    })
  }

  private matchesExcludedRouteChild(url: string): boolean {
    for (let excludedRoute of this.settings.pageTracking.excludedRoutes) {
      if ((excludedRoute instanceof RegExp && excludedRoute.test(url)) || url.indexOf(excludedRoute) > -1) {
        return true;
      }
    }
    return false;
  }
}
```

In the app bootstrap, I add: `provide(Angulartics2, {useClass: Angulartics2Deprecated})`.

It could be simpler, but I wanted to use the most of Angulartics functionality I could.

**Comment by JonnyBGod** [comment] 2016-05-19 13:59
Is this confirmed to be an upstream bug?

If so, we can create a wiki page for @JulioC workaround and reference it on readme.

Can you confirm that the current version is working with the new router?

@JulioC Care to join us as a contributor? I have been really busy lately and would be really helpful to have more devs maintaining this library. @NathanWalker has been helping a lot. Please consider joining us for regular maintenance.

**Comment by JulioC** [comment] 2016-05-19 14:05
Just check https://github.com/angular/angular/issues/8723 and look like it also affects the new router as well.

Thanks for the invite, but I don't feel I have enough open source experience to handle that yet.

**Comment by NathanWalker** [comment] 2016-05-25 03:42
Thanks for posting that issue @JulioC 
Your workaround works but yeah we won't to stay away from importing any `Router` at all in the lib at all costs. We could post in the `README` for time being on wiring to whatever `Router` the end user is using and just call track themselves in their app on their particular router usage.

And then when that issue https://github.com/angular/angular/issues/8723 is addressed, we can the remove that from `README`. This lib is great and I'm dedicated to making it great so am definitely willing to join for regular maintenance @JonnyBGod 

As far as addressing the `README` as stated, if someone could do that this week would be great (maybe just 1 example showing the *new* router and wiring to `router.subscribe((value: any) => {...` to then manually `track` the route changes. I won't have time until mid next week.

**Comment by briananderson1222** [comment] 2016-06-20 14:21
At first glance this appears to be working without the workaround with the latest Angular 2 RC 2. Is this issue still open?

**Comment by JulioC** [comment] 2016-06-22 02:14
I've tested Angulartics2 1.1.1 with Angular RC 2 and as far as I can tell, the issue is not fixed yet.

**Comment by JulioC** [comment] 2016-06-22 02:30
Updating the workaround code:

```ts
import {Location} from '@angular/common';
import {Injectable} from '@angular/core';
import {Router} from '@angular/router-deprecated';
import {Angulartics2} from 'angulartics2';

@Injectable()
export class Angulartics2Deprecated extends Angulartics2 {
  constructor(location: Location, router: Router) {
    super(location);
    this.trackRouter(location, router);
  }

  trackRouter(location: Location, router: Router) {
    router.subscribe((value: any) => {
      let url = location.path();
      this.trackUrlChange(url, location);
    });
  }
}
```

**Comment by briananderson1222** [comment] 2016-06-22 04:19
You're right.. must've been on the branch where I had the workaround implemented :)

If you're using the new router this appears to work for me in the trackRouter method:
```js
    router.events.subscribe((event: any) => {
        if (event instanceof NavigationEnd) {
            let url = location.path();
            this.trackUrlChange(url, location);
        }
    });
```

**Comment by michaelbailey** [comment] 2016-07-12 18:32
Is there a workaround which works with "@angular/router": "3.0.0-alpha.8" ?

**Comment by JulioC** [comment] 2016-07-26 02:46
As given by @briananderson1222, this should work on latest "@angular/router": "3.0.0-beta.2"

```ts
import { Location } from '@angular/common';
import { Injectable } from '@angular/core';
import { Router, NavigationEnd } from '@angular/router';
import { Angulartics2 } from 'angulartics2';

@Injectable()
export class Angulartics2Workaround extends Angulartics2 {
  constructor(location: Location, router: Router) {
    super(location);
    router.events.subscribe((event: any) => {
      if (event instanceof NavigationEnd) {
        let url = location.path();
        this.trackUrlChange(url, location);
      }
    });
  }
}
```

**Comment by icfantv** [comment] 2016-07-26 15:43
I'm missing something really silly here.  How do I wire @JulioC's solution into my application to get the routing events?

**Comment by JulioC** [comment] 2016-07-27 01:25
After adding that class to your project, you can provide it instead as Angulartics2 on your app bootstrap code (the order does matter):

```
import { bootstrap } from '@angular/platform-browser-dynamic';
import { provide } from '@angular/core';
import { Angulartics2 } from 'angulartics2';
import { Angulartics2GoogleAnalytics } from 'angulartics2/src/providers/angulartics2-google-analytics';

import { App } from './app';
import { Angulartics2Workaround } from './angularticsWorkaround.service';

bootstrap(App, [
  // other dependencies
  Angulartics2,
  provide(Angulartics2, {useClass: Angulartics2Workaround}),
  Angulartics2GoogleAnalytics, // your analytics provider
  // other dependencies
])
```

**Comment by icfantv** [comment] 2016-07-27 15:16
@JulioC, that worked, thank you.

**Comment by codedumper** [comment] 2016-08-09 18:35
Angulartics2Workaround works for me, but i had to initialize _gap (for google analytics). Angular2.0rc4 does not like to test uninitialized array.


```
   var _gaq = false;
   ga('create', 'UA-82206039-2', 'auto');
```

As the first test is if(_gap), it works fine. But correct code should probably be _gap=[].

**Comment by JonnyBGod** [comment] 2016-09-01 23:22
I believe this is fixed in https://github.com/angulartics/angulartics2/commit/5c89f50ea7511c8a5b9f4fc131a0b40b883536db

Will leave this open for confirmation for a few weeks.

**Comment by OnlyByGrace** [comment] 2016-09-02 21:57
I'm still having to employ a workaround with d350ed3b8dfe12fb0f2e1f2b98c5b0e7e011b68d.

**Comment by JonnyBGod** [comment] 2016-09-03 01:50
I will have a better look into it tomorrow. It is strange because it passes
tests and triggers location.subscription on test environment.
But for some reason it does not work when integrated to an app.
........

**Comment by RicardoD7I** [comment] 2016-09-08 13:02
Hey guys... are you using the workaround with RC6 ? @JulioC @icfantv

**Comment by JulioC** [comment] 2016-09-08 13:41
We haven't updated our app yet. Probably by the end of the month I can give my vision on this issue

**Comment by icfantv** [comment] 2016-09-08 22:14
@RicardoD7I, no we gave up on this library and are doing it ourselves simply calling the `ga` function directly.  You can see what we did [here](https://github.com/ng-bootstrap/ng-bootstrap) in our demo app.  We just need to know how our library users are using our demo site.

**Comment by RicardoD7I** [comment] 2016-09-08 23:04
Hello @icfantv I saw the demo on ng-bootstrap. Btw.. great job with the library.

I saw the code....
`
  trackPageViews() {
    if (this._enabled) {
      this._router.events.filter((event) => event instanceof NavigationEnd).subscribe(() => {
        ga('send', {hitType: 'pageview', page: this._location.path()});
      });
    }
  }
`

Probably this change (using  this._router.events.filter((event) ) will work on this library @JonnyBGod 
I will keep trying this library, if we can do angulartics2 the place for default analytics in NG2 this will rock! Also I think that this library has lot's of potential. I hope that I can continue helping the author. Also the advanced seed by @NathanWalker works with this library, that is also a great seed.
I have the library working with the angular2seed by mgechev with angulartics2, it just needs a couple of changes to work with the router.

I hope to have some more time on the week to PR the omniture provider!

**Comment by JonnyBGod** [comment] 2016-09-09 04:08
@RicardoD7I I am aware of the problem and yes that would solve the problem and make it work properly with current router.

As discussed above I opted for a router agnostic lib with is not working due to an upstream bug that has been reported a few months ago.

 I realise this is causing a lot of problems and I don't want to feel stubborn. So, I am open to make the necessary changes for the library to work now. This means subscribing to Router instead of Location, and also means that won't work with other routers.

So, I would like to know your opinions on 2 options:

1. Lets wait a bit longer for final release and hope for an upstream fix and keep subscribing to Location. (If after release the bug persists we give up on location)

2. Lets make it work now, subscribing to router and once/if the location bug gets fixed we roll back to subscribing to location.

**Comment by rolandoldengarm** [comment] 2016-09-09 07:37
Option 2!! Definitely. The upstream bug has been raised since RC4(?) and is still not fixed.

**Comment by RicardoD7I** [comment] 2016-09-09 13:13
@JonnyBGod  I love the idea of this library being routing agnostic.
I think that a good idea is to "make it work" (option 2) at this point, so we can move on and start adding more providers and do a bigger tests in different environment.

Probably we should all push for the upstream bug fix :)

**Comment by RicardoD7I** [comment] 2016-09-10 13:19
Probably related :https://github.com/angular/angular/pull/11063

**Closed** 2016-09-11 17:21 UTC

**Comment by JonnyBGod** [comment] 2016-09-11 17:39
Just released a new version working with current RouterV3.

Let me know if you find any issue with it.
