### ISSUE TITLE
Any chance to get documentation fixed!

### ISSUE THREAD

**Issue by almothafar** [angulartics/angulartics2#140] opened 2017-08-09 16:07 UTC
* **I'm submitting a ...**
[X] bug report
[X] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
The problem is a bug because the current documentation is totally useless, the request for more details about GTM, the set up with links provided and the wiki is not working at all.

* **What is the current behavior?**
The first 2 lines working, the _angulartics2 one is not working at all.
```
    const _dataLayer = (window as any).dataLayer = (window as any).dataLayer || [];
    _dataLayer.push({'event': 'Page View', 'content-name': event.url, 'userId': !!this._fbUser ? this._fbUser.uid : undefined});
    // this._angulartics2.pageTrack.next(event.url); // this is not working

```
- Angular version: 4.3.3
- Browser: [all ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by scttcper** [comment] 2017-10-31 18:44
are you defining `_angulartics2: Angulartics2`? What does your code look like?

**Comment by almothafar** [comment] 2017-11-01 07:58
@scttcper yes sure thing :) 

the problem is that the view is not counted, at all, currently, I built my own service and it is working correctly, using this library is not working at all, not working meaning it is compiles, no errors or warnings, it is just not sending any data.

My problem here is that documentation is most important part with this complex GTM and this is got 0 documentation to how things should be to work here.

For GTM setup, I found the steps are not only 3 as the wiki said, it is really like 12 steps to get page view working as for example.

**Comment by scttcper** [comment] 2017-11-01 15:43
```ts
@Component({
  selector: 'app',
  template: `<router-outlet></router-outlet>`
})
export class AppComponent {
  constructor(angulartics2GoogleTagManager: Angulartics2GoogleTagManager) {}
}
```
might have been what you were missing. has to be imported in root component to start the subscription to events.

**Comment by scttcper** [comment] 2017-11-09 19:35
Dupe of #115 I think

**Closed by scttcper** 2017-11-09 19:35 UTC
Labels: duplicate, providers

**Comment by almothafar** [comment] 2017-11-12 09:46
@scttcper It is not duplicate, I think the document must be fixed instead of fishing deep inside issues to know what the solution!
